/* Package version: 0.2.1 */

/*
 * FSRING ABI v2 C declarations.
 *
 * Source of truth: the public wire types and constants in fsring-abi.
 * Regenerate with the exact command documented in README.md.
 */
#if defined(_MSC_VER)
#  define FSRING_ALIGN(N) __declspec(align(N))
#elif defined(__GNUC__) || defined(__clang__)
#  define FSRING_ALIGN(N) __attribute__((aligned(N)))
#else
#  error "FSRING ABI requires a compiler-specific alignment annotation"
#endif


#ifndef FSRING_ABI_H
#define FSRING_ABI_H

/* Generated with cbindgen:0.29.4 */

/* Generated by pinned cbindgen 0.29.4; do not edit manually. */

#include <stdint.h>

#define FSRING_PROTOCOL_FEATURE_PT 0

#define FSRING_PROTOCOL_FEATURE_MMAP 1

#define FSRING_PROTOCOL_FEATURE_HOT_RESTART 2

#define FSRING_PROTOCOL_FEATURE_EXACTLY_ONCE 3

#define FSRING_PROTOCOL_FEATURE_SECURITY 4

#define FSRING_PROTOCOL_FEATURE_REPARSE 5

#define FSRING_PROTOCOL_FEATURE_TOKEN_DONATION 6

#define FSRING_PROTOCOL_FEATURE_MAPPED_IO 7

#define FSRING_PROTOCOL_FEATURE_NOTIFY_NAMES 8

#define FSRING_PROTOCOL_FEATURE_CASE_SENSITIVE_NAMES 9

#define FSRING_OS_CAP_MDL_NO_WRITE 0

#define FSRING_OS_CAP_MDL_NO_EXECUTE 1

#define FSRING_OS_CAP_MODERN_COHERENCY 2

#define FSRING_OS_CAP_ARM64 3

#define FSRING_REQ_INDEX_BITS 24

#define FSRING_REQ_GENERATION_BITS 40

#define FSRING_REQ_INDEX_MAX ((1u << FSRING_REQ_INDEX_BITS) - 1)

#define FSRING_REQ_GENERATION_MAX ((1ull << FSRING_REQ_GENERATION_BITS) - 1)

/**
 * Little-endian integer representation of the ASCII bytes `FSRG`.
 *
 * Keep this as a literal so the pinned C header generator can emit the same
 * value without evaluating a Rust-only `const fn` call.
 */
#define FSRING_MAGIC 1196577606

#define FSRING_ABI_MAJOR 2

#define FSRING_ABI_MINOR 1

/**
 * The oldest ABI minor this build interoperates with. ABI 2.0 is a
 * non-interoperable pre-release; minor 0 is never negotiated, so the minimum
 * compatible minor equals the active minor.
 */
#define FSRING_ABI_MIN_COMPAT_MINOR 1

#define FSRING_ENDIAN_LITTLE 1

#define FSRING_SLOT_CLASS_COUNT 4

#define FSRING_SQE_PAYLOAD_LEN 88

#define FSRING_CQE_OUT_LEN 24

/**
 * Consumer-owned park-state wire values used by the v2 wake protocol.
 */
#define FSRING_PARK_STATE_ACTIVE 0

#define FSRING_PARK_STATE_POLLING 1

#define FSRING_PARK_STATE_PARKED 2

#define FSRING_SLOT_INDEX_MAX ((1u << 20) - 1)

#define FSRING_SLOT_OFFSET_MAX ((1u << 21) - 1)

#define FSRING_SLOT_LENGTH_MAX ((1u << 21) - 1)

#define FSRING_SQE_FLAG_NO_COMPLETION (1 << 0)

#define FSRING_OP_PREPARE_OPEN 1

#define FSRING_OP_COMMIT_OPEN 2

#define FSRING_OP_ABORT_OPEN 3

#define FSRING_OP_CLEANUP 4

#define FSRING_OP_CLOSE 5

#define FSRING_OP_READ 16

#define FSRING_OP_WRITE 17

#define FSRING_OP_FLUSH 18

#define FSRING_OP_QUERY_INFO 32

#define FSRING_OP_MUTATE 33

#define FSRING_OP_QUERY_DIR 34

#define FSRING_OP_QUERY_VOLUME 35

#define FSRING_OP_QUERY_SECURITY 36

#define FSRING_OP_FSCTL 37

#define FSRING_OP_CANCEL 48

#define FSRING_OP_ATTACH 64

#define FSRING_OP_REPLAY_OPEN 65

#define FSRING_OP_QUERY_OP 66

#define FSRING_OP_ACK_RESULT 67

#define FSRING_OP_PT_ROUTE_ACK 80

#define FSRING_OP_PT_EXTERNAL_SAFE_ACK 81

#define FSRING_OP_DIR_CHANGE_ACK 82

#define FSRING_CQ_KIND_COMPLETION 0

#define FSRING_CQ_KIND_NOTIFY 1

#define FSRING_CQ_KIND_PROTOCOL 2

#define FSRING_NOTIFY_INVALIDATE_FILE 1

#define FSRING_NOTIFY_INVALIDATE_ENTRY 2

#define FSRING_NOTIFY_PT_GRANT 3

#define FSRING_NOTIFY_PT_REVOKE_ROUTE 4

#define FSRING_NOTIFY_PT_EXTERNAL_MUTATION_SAFE 5

#define FSRING_NOTIFY_RESIZE 6

#define FSRING_NOTIFY_DIR_CHANGE 7

#define FSRING_NOTIFY_PT_LANE_READY 8

#define FSRING_NOTIFY_EXTERNAL_CHANGE_READY 9

#define FSRING_NOTIFY_EXTERNAL_CHANGE_CUT 10

#define FSRING_CONTROL_SQ_RESERVE_PER_RING 4

#define FSRING_SYSTEM_REQUEST_SLOTS_PER_RING 3

#define FSRING_SYSTEM_REQID_BASE 16777023

#define FSRING_GLOBAL_EXTERNAL_CHANGE_ACK_REQID 16777215

/**
 * Largest nonnegative value that can be represented by a Windows LARGE_INTEGER.
 */
#define FSRING_MAX_FILE_SIZE (uint64_t)INT64_MAX

#define FSRING_CONTROL_VERSION_V1 1

#define FSRING_CONTROL_VERSION_V2 2

#define FSRING_BUFFER_KIND_NONE 0

#define FSRING_BUFFER_KIND_SLOT 1

#define FSRING_BUFFER_KIND_MAPPING 2

#define FSRING_BUFFER_ACCESS_K2U_READ_ONLY 1

#define FSRING_BUFFER_ACCESS_U2K_WRITE 2

#define FSRING_RW_FLAG_PAGING (1 << 0)

#define FSRING_RW_FLAG_NOCACHE (1 << 1)

#define FSRING_RW_FLAG_WRITE_THROUGH (1 << 2)

#define FSRING_RW_FLAG_MAPPED (1 << 3)

#define FSRING_RW_FLAG_SYNC_PAGING (1 << 4)

#define FSRING_RW_FLAG_EXTENDING (1 << 5)

#define FSRING_RW_FLAG_ZERO_RANGE_VALID (1 << 6)

#define FSRING_SLOT_TOKEN_CLASS_MAX 3

#define FSRING_SLOT_TOKEN_INDEX_MAX ((1u << 20) - 1)

#define FSRING_SLOT_TOKEN_GENERATION_MAX ((1ull << 42) - 1)

typedef struct FeatureSet {
    uint64_t words[2];
} FeatureSet;

typedef uint64_t ReqId;

typedef struct OpId {
    uint64_t lo;
    uint64_t hi;
} OpId;

typedef struct FileId {
    uint64_t lo;
    uint64_t hi;
} FileId;

typedef struct LinkId {
    uint64_t lo;
    uint64_t hi;
} LinkId;

typedef struct MountId {
    uint64_t lo;
    uint64_t hi;
} MountId;

typedef struct TransactionId {
    uint64_t lo;
    uint64_t hi;
} TransactionId;

typedef struct AckToken {
    uint64_t lo;
    uint64_t hi;
} AckToken;

/**
 * Packed slot reference: `class:2 | index:20 | offset:21 | len:21`.
 */
typedef uint64_t SlotRef;

typedef struct RegionDesc {
    uint64_t offset;
    uint64_t length;
} RegionDesc;

typedef struct SlotClassDesc {
    uint32_t slot_size;
    uint32_t slot_count;
    uint64_t data_offset;
} SlotClassDesc;

typedef struct FSRING_ALIGN(4096) GlobalHeader {
    uint32_t magic;
    uint16_t header_size;
    uint16_t abi_major;
    uint16_t abi_minor;
    uint8_t byte_order;
    uint8_t header_flags;
    uint32_t page_size;
    uint64_t session_epoch;
    uint64_t section_size;
    uint32_t ring_count;
    uint32_t ring_desc_size;
    struct RegionDesc ring_directory;
    struct RegionDesc k2u_slots;
    struct RegionDesc u2k_slots;
    struct RegionDesc notify_names;
    struct FeatureSet protocol_features;
    struct FeatureSet os_capabilities;
    uint32_t max_inflight;
    uint32_t flags;
    struct SlotClassDesc k2u_slot_classes[FSRING_SLOT_CLASS_COUNT];
    struct SlotClassDesc u2k_slot_classes[FSRING_SLOT_CLASS_COUNT];
    /**
     * Reserved ABI bytes: senders write zero; receivers validate zero.
     */
    uint8_t reserved[3824];
} GlobalHeader;

typedef struct FSRING_ALIGN(64) RingDesc {
    uint32_t magic;
    uint16_t desc_size;
    uint16_t desc_version;
    uint32_t ring_index;
    uint32_t flags;
    uint32_t sq_capacity;
    uint32_t cq_capacity;
    struct RegionDesc sq_entries;
    struct RegionDesc sq_producer;
    struct RegionDesc sq_consumer;
    struct RegionDesc cq_entries;
    struct RegionDesc cq_producer;
    struct RegionDesc cq_consumer;
    /**
     * Reserved ABI bytes: senders write zero; receivers validate zero.
     */
    uint8_t reserved[8];
} RingDesc;

typedef struct FSRING_ALIGN(4096) ProducerPage {
    uint64_t tail;
    uint64_t wake_sequence;
    uint32_t flags;
    /**
     * Explicit alignment bytes: senders write zero; receivers validate zero.
     */
    uint8_t reserved0[4];
    /**
     * Reserved ABI bytes: senders write zero; receivers validate zero.
     */
    uint8_t reserved[4072];
} ProducerPage;

typedef struct FSRING_ALIGN(4096) ConsumerPage {
    uint64_t head;
    uint32_t park_state;
    uint32_t flags;
    uint64_t heartbeat;
    /**
     * Reserved ABI bytes: senders write zero; receivers validate zero.
     */
    uint8_t reserved[4072];
} ConsumerPage;

typedef struct SqeBody {
    uint16_t opcode;
    uint16_t flags;
    uint16_t payload_len;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint16_t reserved;
    uint64_t req_id;
    uint64_t kernel_open_id;
    uint64_t ccb_sequence;
    uint8_t payload[FSRING_SQE_PAYLOAD_LEN];
} SqeBody;

typedef struct FSRING_ALIGN(64) Sqe {
    uint64_t sequence;
    struct SqeBody body;
} Sqe;

typedef struct CqeBody {
    uint16_t kind;
    uint16_t opcode;
    uint16_t flags;
    uint16_t out_len;
    uint64_t req_id;
    int32_t status;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    uint64_t information;
    uint8_t out[FSRING_CQE_OUT_LEN];
} CqeBody;

typedef struct FSRING_ALIGN(64) Cqe {
    uint64_t sequence;
    struct CqeBody body;
} Cqe;

typedef struct ControlHeader {
    uint32_t struct_size;
    uint16_t struct_version;
    uint16_t required_flags;
} ControlHeader;

typedef struct BufferRef {
    uint64_t token;
    uint32_t offset;
    uint32_t length;
    uint16_t kind;
    uint16_t access;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} BufferRef;

typedef struct SizeState {
    uint64_t allocation_size;
    uint64_t file_size;
    uint64_t valid_data_length;
    uint64_t size_epoch;
} SizeState;

typedef struct PControl {
    struct BufferRef body;
} PControl;

typedef struct OControl {
    struct BufferRef body;
} OControl;

typedef struct PBarrier {
    struct OpId op_id;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} PBarrier;

typedef struct PCancel {
    uint64_t target_req_id;
    uint64_t target_session_epoch;
} PCancel;

typedef struct PNotifyAck {
    struct AckToken token;
    uint64_t epoch;
} PNotifyAck;

/**
 * READ uses `OpId::ZERO` plus a U2K-writable buffer; WRITE uses a nonzero
 * operation ID plus a K2U-read-only buffer. Receivers validate that semantic
 * direction after decoding this all-bit-valid wire representation.
 */
typedef struct PRw {
    struct OpId op_id;
    uint64_t offset;
    uint64_t size_epoch;
    uint64_t initialized_offset;
    struct BufferRef data;
    uint32_t length;
    uint32_t initialized_length;
    uint32_t rw_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} PRw;

typedef struct ORw {
    uint64_t file_size;
    uint64_t valid_data_length;
    uint64_t size_epoch;
} ORw;

typedef struct PrepareOpenV1 {
    struct ControlHeader header;
    struct OpId op_id;
    struct FileId parent_id;
    struct BufferRef name;
    uint64_t security_context_id;
    uint32_t desired_access;
    uint32_t share_access;
    uint32_t disposition;
    uint32_t create_options;
    uint32_t file_attributes;
    uint32_t open_flags;
} PrepareOpenV1;

typedef struct PrepareOpenResultV1 {
    struct ControlHeader header;
    struct TransactionId transaction_id;
    struct FileId file_id;
    struct LinkId link_id;
    struct BufferRef security_descriptor;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint32_t object_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} PrepareOpenResultV1;

typedef struct CommitOpenV1 {
    struct ControlHeader header;
    struct OpId op_id;
    struct TransactionId transaction_id;
    uint64_t expected_namespace_generation;
    uint64_t expected_security_generation;
    uint64_t kernel_open_id;
    uint32_t commit_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} CommitOpenV1;

typedef struct CommitOpenResultV1 {
    struct ControlHeader header;
    uint64_t provider_open_cookie;
    struct FileId file_id;
    struct LinkId link_id;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint32_t create_result;
    uint32_t result_flags;
} CommitOpenResultV1;

typedef struct AbortOpenV1 {
    struct ControlHeader header;
    struct TransactionId transaction_id;
} AbortOpenV1;

typedef struct MutationV1 {
    struct ControlHeader header;
    struct OpId op_id;
    uint16_t mutation_kind;
    uint16_t mutation_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    uint64_t expected_namespace_generation;
    uint64_t expected_size_epoch;
    struct BufferRef body;
} MutationV1;

typedef struct MutationResultV1 {
    struct ControlHeader header;
    struct OpId op_id;
    uint64_t volume_commit_sequence;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint32_t result_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} MutationResultV1;

typedef struct ReplayOpenV1 {
    struct ControlHeader header;
    uint64_t kernel_open_id;
    struct FileId file_id;
    struct LinkId link_id;
    uint32_t desired_access;
    uint32_t share_access;
    uint32_t create_options;
    uint32_t disposition;
    uint64_t ccb_sequence;
    uint64_t state_flags;
} ReplayOpenV1;

typedef struct ReplayOpenResultV1 {
    struct ControlHeader header;
    uint64_t provider_open_cookie;
} ReplayOpenResultV1;

typedef struct AttachV1 {
    struct ControlHeader header;
    uint64_t prior_session_epoch;
    struct FeatureSet requested_features;
    struct MountId mount_id;
    uint32_t journal_version;
    uint32_t flags;
} AttachV1;

typedef struct QueryOpV1 {
    struct ControlHeader header;
    struct OpId op_id;
    uint8_t operation_digest[32];
} QueryOpV1;

typedef struct QueryOpResultV1 {
    struct ControlHeader header;
    uint16_t state;
    uint16_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct OpId op_id;
    struct BufferRef result;
} QueryOpResultV1;

typedef struct AckResultV1 {
    struct ControlHeader header;
    struct OpId op_id;
} AckResultV1;

typedef struct NotifyEnvelopeV1 {
    struct ControlHeader header;
    uint16_t notify_code;
    uint16_t notify_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct AckToken token;
    struct FileId file_id;
    struct BufferRef body;
} NotifyEnvelopeV1;

/**
 * Authenticated control-IOCTL payload; never valid on an unestablished ring.
 */
typedef struct DonateBackingV1 {
    struct ControlHeader header;
    struct FileId file_id;
    uint64_t pt_epoch;
    uint64_t daemon_handle;
    uint32_t sector_size;
    uint32_t flags;
} DonateBackingV1;

/**
 * Authenticated control-IOCTL payload; never valid on an unestablished ring.
 */
typedef struct DonateSecurityContextV1 {
    struct ControlHeader header;
    uint64_t security_context_id;
    uint64_t daemon_handle;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} DonateSecurityContextV1;

typedef struct BootInstanceId {
    uint64_t lo;
    uint64_t hi;
} BootInstanceId;

typedef struct RetireToken {
    uint64_t lo;
    uint64_t hi;
} RetireToken;

typedef uint64_t SlotToken;

typedef struct BlobSlice {
    uint32_t offset;
    uint32_t length;
} BlobSlice;

typedef struct SlotClassRequest {
    uint32_t slot_size;
    uint32_t slot_count;
} SlotClassRequest;

typedef struct SetupRequestV1 {
    struct ControlHeader header;
    uint16_t abi_major;
    uint16_t min_abi_minor;
    uint16_t max_abi_minor;
    uint16_t reserved0;
    struct FeatureSet offered_features;
    struct FeatureSet required_features;
    struct FeatureSet required_os_capabilities;
    uint32_t ring_count;
    uint32_t sq_capacity;
    uint32_t cq_capacity;
    uint32_t max_inflight;
    struct SlotClassRequest k2u_slot_classes[FSRING_SLOT_CLASS_COUNT];
    struct SlotClassRequest u2k_slot_classes[FSRING_SLOT_CLASS_COUNT];
    uint32_t notification_credit_count;
    uint32_t notification_credit_size;
    uint32_t flags;
    uint32_t reserved1;
} SetupRequestV1;

typedef struct UserViewDesc {
    uint64_t section_offset;
    uint64_t length;
    uint64_t user_address;
    uint32_t ring_index;
    uint16_t kind;
    uint16_t access;
} UserViewDesc;

typedef struct NotificationCreditV1 {
    struct BufferRef buffer;
    uint32_t ring_index;
    uint32_t reserved;
} NotificationCreditV1;

typedef struct SessionResultV1 {
    struct ControlHeader header;
    uint16_t abi_major;
    uint16_t abi_minor;
    uint32_t reserved0;
    struct MountId mount_id;
    struct BootInstanceId boot_instance_id;
    uint64_t session_epoch;
    uint64_t section_size;
    struct FeatureSet selected_features;
    struct FeatureSet os_capabilities;
    uint32_t view_count;
    uint32_t view_desc_size;
    uint32_t views_offset;
    uint32_t notification_credit_count;
    uint32_t notification_credit_desc_size;
    uint32_t notification_credits_offset;
    uint32_t ring_count;
    uint32_t max_inflight;
    uint32_t flags;
    uint32_t reserved1;
} SessionResultV1;

typedef struct EnterRequestV1 {
    struct ControlHeader header;
    struct MountId mount_id;
    uint64_t session_epoch;
    uint32_t ring_index;
    uint32_t flags;
    uint32_t cq_budget;
    uint32_t timeout_ms;
} EnterRequestV1;

typedef struct EnterResultV1 {
    struct ControlHeader header;
    uint64_t session_epoch;
    uint32_t ring_index;
    uint32_t flags;
    uint32_t cq_drained;
    uint32_t sq_ready;
    uint32_t notification_credit_count;
    uint32_t notification_credit_desc_size;
    uint32_t notification_credits_offset;
    uint32_t reserved;
} EnterResultV1;

typedef struct DetachRequestV1 {
    struct ControlHeader header;
    struct MountId mount_id;
    uint64_t session_epoch;
    uint32_t flags;
    uint32_t reserved;
} DetachRequestV1;

typedef struct DonateBackingV2 {
    struct ControlHeader header;
    struct FileId file_id;
    uint64_t pt_epoch;
    uint32_t sector_size;
    uint32_t flags;
    struct BlobSlice backing_path;
} DonateBackingV2;

typedef struct RetireMountV1 {
    struct ControlHeader header;
    struct MountId mount_id;
    struct RetireToken token;
    uint32_t action;
    uint32_t reserved;
} RetireMountV1;

typedef struct RetireMountResultV1 {
    struct ControlHeader header;
    struct MountId mount_id;
    struct BootInstanceId boot_instance_id;
    struct RetireToken proof_token;
    uint64_t latest_session_epoch;
    struct FeatureSet selected_features;
    uint32_t journal_version;
    uint16_t mount_state;
    uint16_t flags;
    uint64_t reserved;
} RetireMountResultV1;

/**
 * Stable BootContext header wire image.
 *
 * `Pod` applies only to a private, stable record image. Callers must not cast,
 * decode, borrow, or read a live mapped BootContext record. Runtime code must
 * first obtain an accepted private copy through the binding seqlock/barrier
 * protocol.
 */
typedef struct FSRING_ALIGN(64) BootContextHeaderV1 {
    uint64_t magic;
    uint32_t format_version;
    uint32_t header_size;
    uint32_t context_size;
    uint32_t slot_size;
    uint32_t slot_count;
    uint32_t init_state;
    uint32_t flags;
    uint32_t reserved0;
    uint64_t header_sequence;
    uint64_t mount_sequence;
    uint64_t mount_sequence_complement;
    uint64_t load_generation;
    uint64_t load_generation_complement;
    struct BootInstanceId boot_instance_id;
    uint8_t per_boot_retire_key[32];
    uint8_t digest[32];
    uint8_t reserved[96];
} BootContextHeaderV1;

/**
 * Stable BootContext slot wire image.
 *
 * `Pod` applies only to a private, stable record image. Callers must not cast,
 * decode, borrow, or read a live mapped BootContext record. Runtime code must
 * first obtain an accepted private copy through the binding seqlock/barrier
 * protocol.
 */
typedef struct FSRING_ALIGN(64) BootContextSlotV1 {
    uint64_t sequence;
    uint32_t state;
    uint32_t service_sid_length;
    uint64_t load_generation;
    uint64_t mount_sequence;
    struct MountId mount_id;
    struct BootInstanceId boot_instance_id;
    uint64_t latest_session_epoch;
    struct FeatureSet selected_features;
    uint32_t journal_version;
    uint32_t flags;
    uint8_t service_sid[68];
    uint8_t reserved[60];
    uint8_t digest[32];
} BootContextSlotV1;

typedef struct ProviderMountRootV1 {
    uint32_t version;
    uint32_t state;
    struct BootInstanceId boot_instance_id;
    struct MountId mount_id;
    uint64_t latest_session_epoch;
    struct FeatureSet selected_features;
    uint32_t journal_version;
    uint32_t service_sid_length;
    uint8_t service_sid[68];
    uint8_t reserved[4];
    struct RetireToken latest_proof_token;
} ProviderMountRootV1;

typedef struct FSRING_ALIGN(8) DurableChildValueV1 {
    struct ControlHeader header;
    uint16_t value_kind;
    uint16_t state;
    uint32_t flags;
    uint8_t identity_digest[32];
    uint8_t payload_digest[32];
    struct BlobSlice payload;
} DurableChildValueV1;

typedef struct AccountingReservationV1 {
    uint16_t target_child_kind;
    uint16_t flags;
    uint32_t target_key_length;
    uint64_t charged_bytes;
    uint8_t target_key_digest[32];
} AccountingReservationV1;

typedef struct PrepareTxIndexValueV1 {
    struct OpId op_id;
    uint8_t identity_digest[32];
} PrepareTxIndexValueV1;

typedef struct LatestProcessedV1 {
    uint64_t first_ordinal;
    uint64_t through_ordinal;
    uint64_t volume_commit_sequence;
    uint8_t semantic_digest[32];
} LatestProcessedV1;

typedef struct RetireReceiptV1 {
    struct RetireToken retire_token;
    uint32_t state;
    uint8_t reserved[12];
} RetireReceiptV1;

typedef struct OpenRecoveryPayloadV1 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId link_id;
    struct FileId parent_id;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint64_t kernel_open_id;
    uint32_t desired_access;
    uint32_t granted_access;
    uint32_t share_access;
    uint32_t create_options;
    uint32_t file_attributes;
    uint32_t disposition;
    struct BlobSlice name;
    struct BlobSlice security_descriptor;
} OpenRecoveryPayloadV1;

typedef struct PrepareRecoveryPayloadV1 {
    struct ControlHeader header;
    struct FileId parent_id;
    struct TransactionId transaction_id;
    struct FileId result_file_id;
    struct LinkId result_link_id;
    struct SizeState result_sizes;
    uint64_t result_namespace_generation;
    uint64_t result_security_generation;
    uint32_t desired_access;
    uint32_t share_access;
    uint32_t disposition;
    uint32_t create_options;
    uint32_t file_attributes;
    uint32_t open_flags;
    uint32_t result_object_flags;
    uint32_t reserved;
    struct BlobSlice name;
    struct BlobSlice requested_security_descriptor;
    struct BlobSlice ea;
    struct BlobSlice result_security_descriptor;
} PrepareRecoveryPayloadV1;

typedef struct JournalStateV1 {
    struct ControlHeader header;
    struct OpId op_id;
    uint16_t opcode;
    uint16_t mutation_kind;
    uint32_t state;
    uint8_t operation_digest[32];
} JournalStateV1;

typedef struct QueryDirSnapshotPayloadV1 {
    struct ControlHeader header;
    uint8_t pattern_digest[32];
    uint64_t entry_count;
    struct BlobSlice entries;
} QueryDirSnapshotPayloadV1;

typedef struct QueryDirCookiePayloadV1 {
    struct ControlHeader header;
    uint64_t next_cookie;
    uint32_t result_flags;
    uint32_t reserved;
    uint8_t attempt_digest[32];
} QueryDirCookiePayloadV1;

typedef struct PtEpochIntentPayloadV1 {
    struct ControlHeader header;
    uint64_t pt_epoch;
    uint32_t sector_size;
    uint32_t flags;
    struct BlobSlice backing_path;
} PtEpochIntentPayloadV1;

typedef struct PtLanePayloadV1 {
    struct ControlHeader header;
    uint64_t high_watermark;
    struct AckToken latest_token;
    struct FileId latest_file_id;
    uint64_t latest_pt_epoch;
    uint16_t latest_notify_code;
    uint16_t flags;
    uint32_t reserved;
    struct BlobSlice pending_envelope;
} PtLanePayloadV1;

/**
 * Durable committed-result outer prefix; the payload slice begins at byte
 * 40 and contains exactly the matching inner result blob.
 */
typedef struct CommittedResultV1 {
    struct ControlHeader header;
    uint16_t opcode;
    uint16_t result_kind;
    int32_t status;
    uint64_t information;
    struct BlobSlice payload;
    uint64_t volume_commit_sequence;
} CommittedResultV1;

typedef struct CommittedOpenResultV1 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId link_id;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint32_t create_result;
    uint32_t flags;
} CommittedOpenResultV1;

typedef struct CommittedWriteResultV1 {
    struct ControlHeader header;
    struct SizeState sizes;
} CommittedWriteResultV1;

/**
 * Durable committed-mutation prefix; `kind_payload` is `{0,0}` except for
 * RENAME/LINK/UNLINK, whose exact result record follows inline.
 */
typedef struct CommittedMutationResultV1 {
    struct ControlHeader header;
    uint16_t mutation_kind;
    uint16_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    struct BlobSlice kind_payload;
} CommittedMutationResultV1;

typedef struct WriteV2 {
    struct ControlHeader header;
    struct OpId op_id;
    uint64_t offset;
    uint64_t expected_size_epoch;
    uint64_t initialized_offset;
    struct BufferRef data;
    uint32_t length;
    uint32_t initialized_length;
    uint32_t rw_flags;
    uint32_t reserved;
    struct BufferRef reply;
} WriteV2;

typedef struct WriteResultV2 {
    struct ControlHeader header;
    struct SizeState sizes;
    uint64_t volume_commit_sequence;
    uint32_t flags;
    uint32_t reserved;
} WriteResultV2;

typedef struct PrepareOpenV2 {
    struct ControlHeader header;
    struct OpId op_id;
    struct FileId parent_id;
    struct BufferRef name;
    uint64_t security_context_id;
    uint32_t desired_access;
    uint32_t share_access;
    uint32_t disposition;
    uint32_t create_options;
    uint32_t file_attributes;
    uint32_t open_flags;
    struct BufferRef requested_security_descriptor;
    struct BufferRef extended_attributes;
    struct BufferRef reply;
    struct BufferRef result_security_descriptor;
} PrepareOpenV2;

typedef struct CommitOpenV2 {
    struct ControlHeader header;
    struct OpId op_id;
    struct TransactionId transaction_id;
    uint64_t expected_namespace_generation;
    uint64_t expected_security_generation;
    uint64_t kernel_open_id;
    uint32_t commit_flags;
    uint32_t reserved;
    uint32_t granted_access;
    uint32_t reserved2;
    struct BufferRef reply;
} CommitOpenV2;

typedef struct CommitOpenResultV2 {
    struct ControlHeader header;
    uint64_t provider_open_cookie;
    struct FileId file_id;
    struct LinkId link_id;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint32_t create_result;
    uint32_t result_flags;
    uint64_t volume_commit_sequence;
} CommitOpenResultV2;

typedef struct SetBasicInfoV1 {
    struct ControlHeader header;
    int64_t creation_time;
    int64_t last_access_time;
    int64_t last_write_time;
    int64_t change_time;
    uint32_t attributes;
    uint32_t set_mask;
} SetBasicInfoV1;

typedef struct SetSizeV1 {
    struct ControlHeader header;
    uint64_t new_size;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} SetSizeV1;

typedef struct RenameV1 {
    struct ControlHeader header;
    struct LinkId source_link_id;
    struct FileId target_parent_id;
    uint64_t expected_source_parent_generation;
    uint64_t expected_target_parent_generation;
    struct BlobSlice name;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} RenameV1;

typedef struct LinkV1 {
    struct ControlHeader header;
    struct FileId source_file_id;
    struct FileId target_parent_id;
    uint64_t expected_target_parent_generation;
    struct BlobSlice name;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} LinkV1;

typedef struct UnlinkV1 {
    struct ControlHeader header;
    struct LinkId link_id;
    struct FileId parent_id;
    uint64_t expected_parent_generation;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} UnlinkV1;

typedef struct SetSecurityV1 {
    struct ControlHeader header;
    uint32_t security_information;
    uint32_t flags;
    struct BlobSlice security_descriptor;
} SetSecurityV1;

typedef struct SetReparseV1 {
    struct ControlHeader header;
    uint32_t tag;
    uint32_t flags;
    struct BlobSlice reparse_data;
} SetReparseV1;

typedef struct DeleteReparseV1 {
    struct ControlHeader header;
    uint32_t tag;
    uint32_t flags;
} DeleteReparseV1;

/**
 * Registry-only assigned layout; illegal in base 2.1 and accepted by no
 * validator.
 */
typedef struct SetSparseV1 {
    struct ControlHeader header;
    uint32_t sparse;
    uint32_t flags;
} SetSparseV1;

typedef struct MutationV2 {
    struct ControlHeader header;
    struct OpId op_id;
    uint16_t mutation_kind;
    uint16_t mutation_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    uint64_t expected_namespace_generation;
    uint64_t expected_size_epoch;
    uint64_t expected_security_generation;
    struct BufferRef body;
    struct BufferRef reply;
    struct BufferRef kind_result;
} MutationV2;

typedef struct MutationResultV2 {
    struct ControlHeader header;
    struct OpId op_id;
    uint64_t volume_commit_sequence;
    uint16_t mutation_kind;
    uint16_t result_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    struct BufferRef kind_result;
} MutationResultV2;

typedef struct RenameResultV2 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId link_id;
    struct FileId replaced_file_id;
    struct LinkId replaced_link_id;
    uint64_t source_parent_generation;
    uint64_t target_parent_generation;
    uint64_t replaced_namespace_generation;
    uint32_t link_count;
    uint32_t replaced_link_count;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} RenameResultV2;

typedef struct LinkResultV2 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId new_link_id;
    struct FileId replaced_file_id;
    struct LinkId replaced_link_id;
    uint64_t target_parent_generation;
    uint64_t replaced_namespace_generation;
    uint32_t link_count;
    uint32_t replaced_link_count;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} LinkResultV2;

typedef struct UnlinkResultV1 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId removed_link_id;
    uint64_t parent_generation;
    uint32_t remaining_link_count;
    uint32_t flags;
} UnlinkResultV1;

typedef struct QueryInfoV1 {
    struct ControlHeader header;
    uint16_t info_class;
    uint16_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct BufferRef output;
} QueryInfoV1;

typedef struct FileInfoV1 {
    struct ControlHeader header;
    int64_t creation_time;
    int64_t last_access_time;
    int64_t last_write_time;
    int64_t change_time;
    struct SizeState sizes;
    uint64_t namespace_generation;
    uint64_t security_generation;
    uint32_t attributes;
    uint32_t link_count;
    uint32_t reparse_tag;
    uint32_t flags;
} FileInfoV1;

/**
 * Registry-only fixed prefix; the QUERY_DIR version map requires
 * [`QueryDirV2`] in ABI 2.1.
 */
typedef struct QueryDirV1 {
    struct ControlHeader header;
    uint64_t enumeration_cookie;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct BlobSlice pattern;
    struct BufferRef output;
} QueryDirV1;

typedef struct QueryDirV2 {
    struct ControlHeader header;
    uint64_t enumeration_cookie;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct BlobSlice pattern;
    struct BufferRef output;
    uint64_t enumeration_generation;
} QueryDirV2;

typedef struct QueryDirResultV1 {
    struct ControlHeader header;
    uint64_t next_cookie;
    uint32_t flags;
    uint32_t entry_count;
    struct BlobSlice entries;
    uint32_t required_length;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} QueryDirResultV1;

typedef struct DirEntryV1 {
    struct ControlHeader header;
    struct FileId file_id;
    struct LinkId link_id;
    struct SizeState sizes;
    int64_t creation_time;
    int64_t last_access_time;
    int64_t last_write_time;
    int64_t change_time;
    uint64_t namespace_generation;
    uint32_t attributes;
    uint32_t reparse_tag;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct BlobSlice name;
} DirEntryV1;

typedef struct QueryVolumeV1 {
    struct ControlHeader header;
    uint16_t info_class;
    uint16_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct BufferRef output;
} QueryVolumeV1;

typedef struct VolumeSizeInfoV1 {
    struct ControlHeader header;
    uint64_t total_allocation_units;
    uint64_t available_allocation_units;
    uint32_t sectors_per_allocation_unit;
    uint32_t bytes_per_sector;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} VolumeSizeInfoV1;

typedef struct QuerySecurityV1 {
    struct ControlHeader header;
    uint32_t security_information;
    uint32_t flags;
    struct BufferRef output;
} QuerySecurityV1;

/**
 * Registry-only layout; ABI 2.1 registers no FSCTL code and the kernel
 * never emits one.
 */
typedef struct FsctlV1 {
    struct ControlHeader header;
    uint32_t code;
    uint32_t flags;
    struct BufferRef input;
    struct BufferRef output;
} FsctlV1;

/**
 * ABI 2.1 notification envelope carrying an inline `BlobSlice` body at byte 56.
 */
typedef struct NotifyEnvelopeV2 {
    struct ControlHeader header;
    uint16_t notify_code;
    uint16_t notify_flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    struct AckToken token;
    struct FileId file_id;
    struct BlobSlice body;
} NotifyEnvelopeV2;

typedef struct InvalidateFileV1 {
    struct ControlHeader header;
    uint64_t offset;
    /**
     * Zero means the whole stream and requires `offset == 0`.
     */
    uint64_t length;
    uint64_t content_epoch;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} InvalidateFileV1;

typedef struct InvalidateEntryV1 {
    struct ControlHeader header;
    uint64_t namespace_generation;
    /**
     * Inline UTF-16 name; begins at byte 32 and consumes the body tail.
     */
    struct BlobSlice name;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} InvalidateEntryV1;

typedef struct PtGrantV1 {
    struct ControlHeader header;
    uint64_t pt_epoch;
    uint32_t sector_size;
    uint32_t flags;
} PtGrantV1;

typedef struct PtEpochV1 {
    struct ControlHeader header;
    uint64_t pt_epoch;
} PtEpochV1;

typedef struct ResizeV1 {
    struct ControlHeader header;
    struct SizeState sizes;
    uint64_t volume_commit_sequence;
} ResizeV1;

/**
 * External directory-change notification body; 176-byte fixed prefix, with
 * body-relative old/new names beginning at byte 176.
 */
typedef struct ExternalDirChangeV1 {
    struct ControlHeader header;
    uint64_t first_ordinal;
    uint64_t through_ordinal;
    uint64_t volume_commit_sequence;
    uint16_t change_kind;
    uint16_t object_kind;
    uint32_t filter_match;
    uint32_t flags;
    uint32_t reserved0;
    struct LinkId target_link_id;
    struct FileId replaced_file_id;
    struct LinkId replaced_link_id;
    struct FileId old_parent_id;
    struct FileId new_parent_id;
    uint64_t old_parent_generation;
    uint64_t new_parent_generation;
    uint64_t target_namespace_generation;
    uint64_t replaced_namespace_generation;
    struct BlobSlice old_name;
    struct BlobSlice new_name;
} ExternalDirChangeV1;

typedef struct PtLaneReadyV1 {
    struct ControlHeader header;
    uint16_t kind_ordinal;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint16_t reserved0;
    uint32_t flags;
    uint64_t high_watermark;
} PtLaneReadyV1;

typedef struct ExternalChangeReadyV1 {
    struct ControlHeader header;
    uint64_t reconcile_cut;
    uint64_t processed_high_watermark;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} ExternalChangeReadyV1;

typedef struct ExternalChangeCutV1 {
    struct ControlHeader header;
    uint64_t reconcile_cut;
    uint32_t flags;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
} ExternalChangeCutV1;

/**
 * `DIR_CHANGE_ACK` SQE-inline payload; `PControl`/`BufferRef` forms are illegal.
 */
typedef struct PDirChangeAckV1 {
    struct AckToken token;
    uint64_t through_ordinal;
    uint64_t volume_commit_sequence;
    uint8_t semantic_digest[32];
} PDirChangeAckV1;

typedef struct ProtocolAbortV1 {
    struct ControlHeader header;
    uint32_t reason;
    /**
     * Reserved ABI field: senders write zero; receivers validate zero.
     */
    uint32_t reserved;
    /**
     * Diagnostic data only; never an address, handle, token, or authority.
     */
    uint64_t context;
} ProtocolAbortV1;

typedef struct ReplayOpenV2 {
    struct ControlHeader header;
    uint64_t kernel_open_id;
    struct FileId file_id;
    struct LinkId link_id;
    uint32_t desired_access;
    uint32_t share_access;
    uint32_t create_options;
    uint32_t disposition;
    uint64_t ccb_sequence;
    uint64_t state_flags;
    struct BufferRef reply;
} ReplayOpenV2;

typedef struct QueryOpV2 {
    struct ControlHeader header;
    struct OpId op_id;
    uint8_t operation_digest[32];
    struct BufferRef reply;
    struct BufferRef committed_result;
} QueryOpV2;

typedef struct AckResultV2 {
    struct ControlHeader header;
    struct OpId op_id;
    uint8_t operation_digest[32];
} AckResultV2;

#endif  /* FSRING_ABI_H */

#undef FSRING_ALIGN
